blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'

urlpatterns = [
  	url(r'^$', views.post_list, name='post_list'),
	url(r'^new/$', views.post_new, name='post_new'),

	url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',views.post_detail, name='post_detail'),

	#url(r'^$', views.PostListView.as_view(), name='post_list'),
	url(r'^(?P<post_id>\d+)/share/$', views.post_share,  name='post_share'),
	url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

notansecreto/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls')),


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):

	def get_queryset(self):
		return super(PublishedManager, self).get_queryset()\
				.filter(status='published')

class Post(models.Model):
	STATUS_CHOICES = (
			('draft', 'Draft'),
			('published', 'Published'),
			)
	title = models.CharField(max_length=250)
	slug = models.SlugField(max_length=250, unique_for_date="publish")
	author = models.ForeignKey(User, related_name='blog_posts', on_delete=models.CASCADE)
	image = models.FileField(null=True, blank=True)
	link = models.URLField(blank=True, null=True)
	body = models.TextField(blank=True)
	publish = models.DateTimeField(default=timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="published")
	objects = models.Manager()
	published = PublishedManager()
	tags = TaggableManager()

	class Meta:
		ordering = ('-publish', )

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:post_detail', args=[self.publish.year, 
			self.publish.strftime('%m'),
			self.publish.strftime('%d'),
			self.slug])
		
class Comment(models.Model):
		post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
		name = models.CharField(max_length=80)
		body = models.TextField(blank=True,max_length=200)
		created = models.DateTimeField(auto_now_add=True)
		updated = models.DateTimeField(auto_now=True)
		active = models.BooleanField(default=True)
		
class Meta:
		ordering = ('created',)
def __str__(self):
	return 'Comment by {} on {}'.format(self.name, self.post)

class About_me(models.Model):
		name = models.CharField(max_length=80)
		avatar = models.FileField(null=True, blank=True)
		body = models.TextField(blank=True)

		class Meta:
			verbose_name_plural = 'About_me'

class Title(models.Model):
		first = models.CharField(max_length=100)
		second = models.CharField(max_length=100)

		class Meta:
			verbose_name_plural = 'Title'


	
	

blog/forms.py
from django import forms
from .models import Comment
from .models import Post
from django.forms import TextInput, Textarea

class EmailPostForm(forms.Form):
	name = forms.CharField(max_length=25)
	to = forms.EmailField()
	comments = forms.CharField(required=False, widget=forms.Textarea)
class CommentForm(forms.ModelForm):
	name = forms.CharField(label="",widget=forms.TextInput(attrs={'placeholder': 'Tu nombre','class' : 'myfieldclass'}))
	body = forms.CharField(label="",widget=forms.Textarea(attrs={'placeholder': 'Tu commentario','style': 'width:75%','class' : 'myfieldclass'}))

	class Meta:
		model = Comment
		fields = ('name', 'body')
		



class PostForm(forms.ModelForm):

	class Meta:
		model = Post
		fields = ('title', 'body',)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .models import Post
from .forms import EmailPostForm
from django.core.mail import send_mail
from .models import Post, Comment, About_me, Title
from .forms import EmailPostForm, CommentForm
from taggit.models import Tag
from django.db.models import Count
from django.contrib.auth import authenticate, login



def post_list(request, tag_slug=None):
             object_list = Post.published.all()
             tag = None
             tags = Tag.objects.all()
             abouts = About_me.objects.all()
             titles = Title.objects.all()

             if tag_slug:
                tag =get_object_or_404(Tag, slug=tag_slug)
                object_list = object_list.filter(tags__in=[tag])

             paginator = Paginator(object_list, 5) # 3 posts in each page
             page = request.GET.get('page')
             try:
                posts = paginator.page(page)
             except PageNotAnInteger:
                     # If page is not an integer deliver the first page
                posts = paginator.page(1)
             except EmptyPage:
                     # If page is out of range deliver last page of results
                posts = paginator.page(paginator.num_pages)
             return render(request,'blog/post/list.html',  {'page': page, 'posts': posts, 'tag': tag,'tags': tags,'abouts':abouts,'titles':titles})

class PostListView(ListView):
        queryset = Post.published.all()
        context_object_name = 'posts'
        paginate_by = 5
        template_name = 'blog/post/list.html'

def post_detail(request, year, month, day, post):
        titles = Title.objects.all()
        tags = Tag.objects.all()
        post = get_object_or_404(Post, slug=post, status='published')
        comments = post.comments.filter(active=True)
        if request.method == 'POST':
           # A comment was posted
            comment_form = CommentForm(data=request.POST)
            if comment_form.is_valid():
# Create Comment object but don't save to database
                new_comment = comment_form.save(commit=False)
 # Assign the current post to the comment
                new_comment.post = post
 # Save the comment to the database
                new_comment.save()
 # new form
                comment_form = CommentForm()

                
        else:
            comment_form = CommentForm()
            post_tags_ids = post.tags.values_list('id', flat=True)
            
            

        return render(request,'blog/post/detail.html',{'post': post,'comments': comments, 'comment_form': comment_form,'tags': tags,'titles':titles})

def post_new(request):
    form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})
def post_share(request, post_id):
        post = get_object_or_404(Post, id=post_id, status='published')
        sent = False
        if request.method == 'POST':
           # Form was submitted
            form = EmailPostForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                post_url = request.build_absolute_uri(post.get_absolute_url())
                subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
                message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
                send_mail(subject, message, 'admin@myblog.com',[cd['to']])
                sent = True
        else:
                form = EmailPostForm()
        return render(request, 'blog/post/share.html', {'post': post,'form': form,'sent': sent})    

blog/templates/blog/base.html
<!DOCTYPE html>
{% load blog_tags %}
{% load static from staticfiles %}
<html>
<title>No tan Secreto</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link href="https://fonts.googleapis.com/css?family=Kelly+Slab|Rakkas&display=swap" rel="stylesheet">
<style>
 


header {
  position: relative;
  background: url(https://elenacube.s3-eu-west-1.amazonaws.com/media/background.png) no-repeat;
  background-size: 100% 100%;
  height: 90%;


}
a { text-decoration: none; }

body,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
h1 {font-family: 'Rakkas', cursive;}

</style>

<body class="w3-light-grey">

<!-- w3-content defines a container for fixed size centered content, 
and is wrapped around the whole page content, except for the footer in this example -->
<div class="w3-content" style="max-width:1400px">

<!-- Header -->

<!-- Blog entries -->
{% block content %}
    {% endblock %}
<!-- Introduction menu -->

<!-- END Introduction Menu -->

</body>
</html>

blog/templates/blog/post/detail.html
<!DOCTYPE html>
{% load blog_tags %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

<html>
<title>No tan Secreto</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link href="https://fonts.googleapis.com/css?family=Kelly+Slab|Rakkas&display=swap" rel="stylesheet">

<style>
 


header {
  position: relative;
  background: url(https://elenacube.s3-eu-west-1.amazonaws.com/media/background.png) no-repeat;
  background-size: 100% 100%;
  position: fixed;
  width: 100%;
  z-index: 1;

}

.myfieldclass{
  background-color: #FAFAF7;
  border-color: transparent;
}
body,h3,h4,h5 {font-family: "Raleway", sans-serif}
h1,h2 {font-family: 'Rakkas', cursive;}
a { text-decoration: none; }

</style>

<body class="w3-light-grey">

<!-- w3-content defines a container for fixed size centered content, 
and is wrapped around the whole page content, except for the footer in this example -->
<div class="w3-content" style="max-width:1400px">
<header class="w3-container w3-center w3-padding-20">
  {% for title in titles %}
   <a class="navbar-brand js-scroll-trigger" href="/"><h2><b>{{ title.first }}</b></h2><a>
  {% endfor %}
</header>
<!-- Blog entries -->
<br><br><br>

<div class="w3-col l8 s12">
  <!-- Blog entry -->
  <div class="w3-card-4 w3-margin w3-white">    
  </div>
  

  <!-- Blog entry -->
  <div class="w3-card-4 w3-margin w3-white">   
    <div class="w3-container">
      <h3><b>{{ post.title }}</b></h3>
        
      <h5><span class="w3-opacity">{{ post.author }},&nbsp;{{ post.publish|date:"M d-Y"}}</span></h5>
    </div>
    <div class="w3-container">
      <p>{{ post.body }}</p> 
       {% if post.link %}
        <a target="_blank" rel="noopener noreferrer" href="{{ post.link }}"> <button class="w3-button w3-white w3-border w3-border-gray">Ver enlance</button></p></a>
         {% endif %}
        {% for tag in post.tags.all %}
       Etiqueta:&nbsp;<a href="{% url "blog:post_list_by_tag" tag.slug %}" style="text-decoration: underline;"><strong>{{  tag.name }}</strong></a> 
       {% if not forloop.last %}, {% endif %}
     {% endfor %}

      <div class="w3-row">
        <div class="w3-col m8 s12">
          <p></p>
        </div>
        <div class="w3-col m4 ">
          <p><span class="w3-padding-small w3-right"><b>Comentarios  </b> <span class="w3-tag" style="padding-bottom: 1px">{{ post.comments.count }}</span></p>
        </div>
      </div>
    </div>
  </div>
    <!-- Comment Card -->
  <div class="w3-card-4 w3-margin w3-white">  
    <div class="w3-container">
     {% if new_comment %}
      <center><h2>Your comment has been added.</h2></center>
     {% else %}
     <center> <h5 style="background-color: #FFED5B"><b>Escribe un comentario!</b></h5>
      <form  method="post">
        {{ comment_form.as_p }}
        {% csrf_token %}
        <span class="w3-padding-small w3-right"><button class="w3-button  w3-white w3-border" type="submit">Enviar</button></span><br><br>
       </form>
      </center><br>
     {% endif %}
    </div>
  </div>
  <!-- Comments Card -->
  {% for comment in comments %}
  <div class="w3-card-4 w3-margin w3-white">  
    <div class="w3-container" >
     {{ comment.body|linebreaks }} <hr>
     Escrito por:&nbsp;<strong>{{ comment.name }}</strong>,&nbsp;{{ comment.created|date:"M d, Y"}}<br>
    <br>
    </div>
  </div>
  {% endfor %}
</div>

<div class="w3-col l4">
  <!-- About Card -->
  <div class="w3-card w3-margin w3-margin-top" style="width:92%">
   {% if post.image %}
   <img class="img-fluid" src="{{ post.image.url }}" alt="image" style="width:100%">
    {% endif %}    
  </div> 
 <!-- Posts -->
  <div class="w3-card w3-margin">
    <div class="w3-container w3-padding">
      <h4>Posts más populares</h4>
    </div>
    {% get_most_commented_posts as most_commented_posts %}
    {% for post in most_commented_posts %}
    <ul class="w3-ul w3-hoverable w3-white">
      <li class="w3-padding-16">
      {% if post.image %}
       <img class="img-fluid" src="{{ post.image.url }}" alt="image" class="w3-left w3-margin-right" style="width:60px">
      {% endif %}     
      <span class="w3-large"><a href="{{ post.get_absolute_url }}">{{ post.title|truncatewords:2 }}</a></span>
      <span style="float: right">{{ post.publish|date:"M d, Y" }}</span><br>
      </li>
      {% endfor %}
    </ul>
  </div>
  <hr> 
  <!-- Labels / tags -->
  <div class="w3-card w3-margin">
    <div class="w3-container w3-padding">
      <h4>Etiquetas</h4>
    </div>
    <div class="w3-container w3-white">    
    <p>{% for tag in tags %}<span class="w3-tag w3-black"><a href="{% url "blog:post_list_by_tag" tag.slug %}">{{  tag.name }}</a></span>
   {% endfor %} </p>
    </div>
  </div>
 
</div>

</div>

<!-- END GRID -->

</div>


</div>

<!-- END w3-content -->
<!-- Footer -->


</body>

</html>

blog/templates/blog/post/latest_posts.html
   <ul>
   	{% for post in latest_posts %}
     <li><a href="{{ post.get_absolute_url }}"> <h6>{{ post.title }}</h6></a>
      </li>
   {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block content %}
<header class="w3-container w3-center w3-padding-32"> {% for title in titles %}
  <h1><b>{{ title.first }}</b></h1>
   <span class="w3-tag">{{ title.second }}</span></p>{% endfor %}
</header>

<!-- Grid -->
<div class="w3-row">

<!-- Blog entries -->
<div class="w3-col l8 s12">
  <!-- Blog entry -->
  <div class="w3-card-4 w3-margin w3-white">  
  </div>
  <!-- Blog entry -->
  {% for post in posts %}
  <div class="w3-card-4 w3-margin w3-white">
    {% if post.image %}
    <a href="{{ post.get_absolute_url }}"><img class="img-fluid" src="{{ post.image.url }}" alt="image"style="width:100%"></a>
    {% endif %}
    <div class="w3-container">
      <h3><b>{{ post.title }}</b></h3>
      <h5><span class="w3-opacity">{{ post.author }},&nbsp;{{ post.publish|date:"M d-Y"}}</span></h5>
    </div>

    <div class="w3-container">
      <p>{{ post.body|truncatewords:30|linebreaks }}</p>
                {% for tag in post.tags.all %}
       Etiqueta:&nbsp;<a href="{% url "blog:post_list_by_tag" tag.slug %}" style="text-decoration: underline;"><strong>{{  tag.name }}</strong></a> 
       {% if not forloop.last %}, {% endif %}
     {% endfor %}
      <div class="w3-row">
        <div class="w3-col m8 s12">
          <p><a href="{{ post.get_absolute_url }}"><button class="w3-button  w3-white w3-border"><b>LEER MÁS »</b></button></p></a>
        </div>
        <div class="w3-col m4">
          <p><span class="w3-padding-small w3-right"><b>Comentarios  </b> <span class="w3-tag" style="padding-bottom: 1px">{{ post.comments.count }}</span></p>
        </div>
      </div>
    </div>
  </div> 
  {% endfor %}
<!-- END BLOG ENTRIES -->
</div>
<div class="w3-col l4">
  <!-- About Card -->
  <div class="w3-card w3-margin w3-margin-top">
   {% for about_me in abouts %}
  <img src="{{ about_me.avatar.url }}" style="width:100%">
    <div class="w3-container w3-white">
      <h1><b>{{ about_me.name }}</b></h1>
      <p>{{ about_me.body }}</p>
      {% endfor %}
    </div>
  </div><hr>
  
  <!-- Posts -->
  <div class="w3-card w3-margin">
    <div class="w3-container w3-padding">
      <h4>Posts más populares</h4>
    </div>
    {% get_most_commented_posts as most_commented_posts %}
  {% for post in most_commented_posts %}
    <ul class="w3-ul w3-hoverable w3-white">
      <li class="w3-padding-16">
         {% if post.image %}
    <img class="img-fluid" src="{{ post.image.url }}" alt="image" class="w3-left w3-margin-right" style="width:60px">
    {% endif %}      
     <a href="{{ post.get_absolute_url }}"><span class="w3-large">{{ post.title|truncatewords:2 }}</span></a>
        <span style="float: right">{{ post.publish|date:"M d, Y" }}</span><br>
      </li>
       {% endfor %}
    </ul>
  </div>
  <hr> 
 
  <!-- Labels / tags -->
  <div class="w3-card w3-margin">
    <div class="w3-container w3-padding">
      <h4>Etiquetas</h4>
    </div>
    <div class="w3-container w3-white">    
    <p>{% for tag in tags %}<span class="w3-tag w3-black"><a href="{% url "blog:post_list_by_tag" tag.slug %}">{{  tag.name }}</a></span>
   {% endfor %} </p>
    </div>
  </div>
           
</div>

<!-- END GRID -->
</div>

<!-- END w3-content -->
</div>
   
<!-- Footer -->
<footer class="w3-container w3-indigo w3-padding-32 w3-margin-top">
  {% include "pagination.html" with page=posts %}
  
</footer>
     

 
{% endblock %}

blog/templates/blog/post/post_detail.html
<!DOCTYPE html>
<html>
<title>Restaurante Julia</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"><body>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<!-- Header -->
<div class="bs-example">
    <nav class="navbar navbar-default">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand"><i class="fa fa-cutlery"></i></a>
        </div>
        <!-- Collection of nav links and other content for toggling -->
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'shop:product_listen' %}">Productos</a></li>
                <li><a href="">Gestion</a></li>
                <li class="active"><a href="{% url 'blog:post_list' %}">Reservas</a></li><li>
                <a href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span> Editar</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Login</a></li>
            </ul>
        </div>
    </nav>
</div>
  <div class="container"><h3>
<a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title|linebreaks }}</a></h3>
        <p><h4>{{ post.text|linebreaks }}</h4></p>{% if post.published_date %}
        <p class="tags">
     {% for tag in post.tags.all %}
       <a href="{% url "blog:post_list_by_tag" tag.slug %}">
         {{ tag.name }}
       </a>
       {% if not forloop.last %}, {% endif %}
     {% endfor %}
</p>
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
	</div>

blog/templates/blog/post/post_edit.html
<!DOCTYPE html>
<html>
<title>Restaurante Julia</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"><body>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<style type="text/css">
    .bs-example{
      margin: 20px;
    }

</style>

<!-- Header -->
<div class="bs-example">
    <nav class="navbar navbar-default">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand"><i class="fa fa-cutlery"></i></a>
        </div>
        <!-- Collection of nav links and other content for toggling -->
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'shop:product_listen' %}">Productos</a></li>
                <li><a href="">Gestion</a></li>
                <li class="active"><a href="{% url 'blog:post_list' %}">Reservas</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Login</a></li>
            </ul>
        </div>
    </nav>
</div>
  <div class="container">
      <h3>Reserva</h3>

	 <form class="" action="./" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit"class="btn btn-info " name="submit" value="Guardar">
  </form>
    </div>
   

blog/templates/blog/post/post_list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load static from staticfiles %}

{% block content %}
<!-- Blog entries -->
<div class="w3-col l8 s12">
  <!-- Blog entry -->
  <div class="w3-card-4 w3-margin w3-white">
    <img src="/w3images/woods.jpg" alt="Nature" style="width:100%">
    <div class="w3-container">
      <h3><b>TITLE HEADING</b></h3>
      <h5>Title description, <span class="w3-opacity">April 7, 2014</span></h5>
    </div>

    <div class="w3-container">
      <p>Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed mattis nunc id lorem euismod placerat. Vivamus porttitor magna enim, ac accumsan tortor cursus at. Phasellus sed ultricies mi non congue ullam corper. Praesent tincidunt sed
        tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.</p>
      <div class="w3-row">
        <div class="w3-col m8 s12">
          <p><button class="w3-button w3-padding-large w3-white w3-border"><b>READ MORE »</b></button></p>
        </div>
        <div class="w3-col m4 w3-hide-small">
          <p><span class="w3-padding-large w3-right"><b>Comments  </b> <span class="w3-tag">0</span></span></p>
        </div>
      </div>
    </div>
  </div>
  <hr>

  <!-- Blog entry -->
  <div class="w3-card-4 w3-margin w3-white">
  <img src="/w3images/bridge.jpg" alt="Norway" style="width:100%">
    <div class="w3-container">
      <h3><b>BLOG ENTRY</b></h3>
      <h5>Title description, <span class="w3-opacity">April 2, 2014</span></h5>
    </div>

    <div class="w3-container">
      <p>Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed mattis nunc id lorem euismod placerat. Vivamus porttitor magna enim, ac accumsan tortor cursus at. Phasellus sed ultricies mi non congue ullam corper. Praesent tincidunt sed
        tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.</p>
      <div class="w3-row">
        <div class="w3-col m8 s12">
          <p><button class="w3-button w3-padding-large w3-white w3-border"><b>READ MORE »</b></button></p>
        </div>
        <div class="w3-col m4 w3-hide-small">
          <p><span class="w3-padding-large w3-right"><b>Comments  </b> <span class="w3-badge">2</span></span></p>
        </div>
      </div>
    </div>
  </div>
<!-- END BLOG ENTRIES -->
</div>


	{% endfor %}

{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
   {% block title %}Share a post{% endblock %}
   {% block content %}
     {% if sent %}
       <h1>E-mail successfully sent</h1>
       <p>
         "{{ post.title }}" was successfully sent to {{ cd.to }}.
       </p>
     {% else %}
       <h1>Share "{{ post.title }}" by e-mail</h1>
       <form action="." method="post">
         {{ form.as_p }}
         {% csrf_token %}
         <input type="submit" value="Send e-mail">
       </form>
     {% endif %}
   {% endblock %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
    {% if page.has_previous %}
    <a href="?page={{page.previous_page_number}}">
    <button style="background-color:white; border-color:#3E4FB2;">Anterior</button></a>
        {% endif %}
    <span class="current">
     Página {{page.number }} de {{ page.paginator.num_pages }}</span>
    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}">
    <button style="background-color:white; border-color:#3E4FB2;">Siguiente </button></a>
        {% endif %}
    </span>
</div>